ITENS_CHECKLIST = {
    "🔴 Pneus e Rodas": [
        "Pneu dianteiro esquerdo — estado e calibragem",
        "Pneu dianteiro direito — estado e calibragem",
        "Pneu traseiro esquerdo — estado e calibragem",
        "Pneu traseiro direito — estado e calibragem",
        "Estepe — estado e calibragem",
        "Macaco e chave de roda",
        "Triângulo de sinalização",
    ],
    "🟡 Lataria e Vidros": [
        "Para-brisa — trincas ou rachaduras",
        "Vidros laterais",
        "Vidro traseiro",
        "Retrovisores (esquerdo, direito e interno)",
        "Lataria — amassados ou danos visíveis",
        "Portas — abertura, fechamento e travas",
        "Tampa do capô",
        "Tampa do porta-malas / caçamba",
        "Para-choque dianteiro",
        "Para-choque traseiro",
    ],
    "💡 Iluminação": [
        "Farol dianteiro esquerdo",
        "Farol dianteiro direito",
        "Luz de milha / auxiliar",
        "Pisca-alerta dianteiro esquerdo",
        "Pisca-alerta dianteiro direito",
        "Pisca-alerta traseiro esquerdo",
        "Pisca-alerta traseiro direito",
        "Luz de freio esquerda",
        "Luz de freio direita",
        "Luz de ré",
        "Luz de placa",
        "Luz interna da cabine",
    ],
    "🔧 Motor e Fluidos": [
        "Nível de óleo do motor",
        "Nível de água / fluido de arrefecimento",
        "Nível do fluido de freio",
        "Nível do fluido da direção hidráulica",
        "Nível do fluido do limpador de para-brisa",
        "Correia dentada / acessórios — estado visível",
        "Vazamentos visíveis (óleo, água, combustível)",
        "Bateria — terminais e fixação",
        "Filtro de ar — estado visível",
    ],
    "🚿 Limpadores e Para-brisa": [
        "Limpador de para-brisa dianteiro esquerdo",
        "Limpador de para-brisa dianteiro direito",
        "Limpador traseiro (se houver)",
        "Esguicho de água dianteiro",
        "Esguicho de água traseiro (se houver)",
    ],
    "🪑 Interior e Cabine": [
        "Bancos — estado e fixação",
        "Cinto de segurança — todos os lugares",
        "Painel — funcionamento dos indicadores",
        "Ar-condicionado",
        "Buzina",
        "Pedais (freio, embreagem, acelerador)",
        "Freio de mão / freio de estacionamento",
        "Volante",
        "Teto / forro interno",
        "Extintor de incêndio (prazo e carga)",
    ],
    "⚙️ Suspensão e Direção": [
        "Direção — folga e ruídos",
        "Suspensão dianteira — ruídos e estado",
        "Suspensão traseira — ruídos e estado",
        "Amortecedores — vazamentos visíveis",
    ],
    "🛑 Freios": [
        "Freio de serviço — eficiência",
        "Freio de estacionamento — eficiência",
        "Ruídos ao frear",
    ],
    "🔩 Câmbio, Motor e Embreagem": [
        "Câmbio — troca de marchas (suavidade e engate)",
        "Câmbio — vazamento de óleo",
        "Embreagem",
        "Motor — ruídos anormais em marcha lenta",
        "Motor — trepidação / falhas de aceleração",
        "Motor — fumaça excessiva no escapamento",
        "Motor — dificuldade na partida a frio",
        "Motor — coxins / suportes do motor",
    ],
}

# Itens adicionais para Van / Sprinter
ITENS_VAN = {
    "🚐 Van / Sprinter (adicional)": [
        "Portas laterais de passageiro — abertura e fechamento",
        "Cintos de segurança dos passageiros",
        "Bancos dos passageiros — fixação",
        "Iluminação interna traseira",
        "Calefação / ventilação traseira",
    ]
}